### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by henriquearthur** [henriquearthur/sublime-settings#1]
**This can easily be your first contribution to open-source world.**

The goal of this repo is to keep my Sublime Text 3 config files saved, so I can easily pull the files on any computer or a fresh OS install.

However, there is a lot of unnecessary files and folders included. They shouldn't be here, because Sublime will download them based on the config json files.

Remove the unnecessary files from the repo, which includes `Color Highlighter`, `SublimeLinter` and some `.sublime-settings` files. Analyse what should be removed and remove it.

Also, add it to `.gitignore` or they will be here again in my next commit.

**Comment by Dheeraj1998** [comment]
I will start working on it!

**Comment by henriquearthur** [comment]
Solved in 687c9c219b494203cf0fab79231be2dd22e7581f
